'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.115;Initial Catalog=DMS;User ID=nelson;Password=P@ssw0rd")>  _
        Public ReadOnly Property DMSConnectionString() As String
            Get
                Return CType(Me("DMSConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\ATLAS_SYNOLOGY\Public\Local Batches\Awaiting Index")>  _
        Public ReadOnly Property ImgPath() As String
            Get
                Return CType(Me("ImgPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoTS() As String
            Get
                Return CType(Me("Save_RackNoTS"),String)
            End Get
            Set
                Me("Save_RackNoTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoTS() As String
            Get
                Return CType(Me("Save_BoxNoTS"),String)
            End Get
            Set
                Me("Save_BoxNoTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoRI() As String
            Get
                Return CType(Me("Save_RackNoRI"),String)
            End Get
            Set
                Me("Save_RackNoRI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoRI() As String
            Get
                Return CType(Me("Save_BoxNoRI"),String)
            End Get
            Set
                Me("Save_BoxNoRI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BookletNoRI() As String
            Get
                Return CType(Me("Save_BookletNoRI"),String)
            End Get
            Set
                Me("Save_BookletNoRI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoWarranty() As String
            Get
                Return CType(Me("Save_RackNoWarranty"),String)
            End Get
            Set
                Me("Save_RackNoWarranty") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoWarranty() As String
            Get
                Return CType(Me("Save_BoxNoWarranty"),String)
            End Get
            Set
                Me("Save_BoxNoWarranty") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoVoucher() As String
            Get
                Return CType(Me("Save_RackNoVoucher"),String)
            End Get
            Set
                Me("Save_RackNoVoucher") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoVoucher() As String
            Get
                Return CType(Me("Save_BoxNoVoucher"),String)
            End Get
            Set
                Me("Save_BoxNoVoucher") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoCorpDocu() As String
            Get
                Return CType(Me("Save_RackNoCorpDocu"),String)
            End Get
            Set
                Me("Save_RackNoCorpDocu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoCorpDocu() As String
            Get
                Return CType(Me("Save_BoxNoCorpDocu"),String)
            End Get
            Set
                Me("Save_BoxNoCorpDocu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.0.115")>  _
        Public Property remoteTOD() As String
            Get
                Return CType(Me("remoteTOD"),String)
            End Get
            Set
                Me("remoteTOD") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\ATLAS_SYNOLOGY\Public\NELSON\@1_REQUEST SKU\DONE\DOWNLOADED")>  _
        Public ReadOnly Property Queue() As String
            Get
                Return CType(Me("Queue"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoImport() As String
            Get
                Return CType(Me("Save_RackNoImport"),String)
            End Get
            Set
                Me("Save_RackNoImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoImport() As String
            Get
                Return CType(Me("Save_BoxNoImport"),String)
            End Get
            Set
                Me("Save_BoxNoImport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoBIR() As String
            Get
                Return CType(Me("Save_RackNoBIR"),String)
            End Get
            Set
                Me("Save_RackNoBIR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoBIR() As String
            Get
                Return CType(Me("Save_BoxNoBIR"),String)
            End Get
            Set
                Me("Save_BoxNoBIR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoHRDoc() As String
            Get
                Return CType(Me("Save_RackNoHRDoc"),String)
            End Get
            Set
                Me("Save_RackNoHRDoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoHRDoc() As String
            Get
                Return CType(Me("Save_BoxNoHRDoc"),String)
            End Get
            Set
                Me("Save_BoxNoHRDoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoBoard() As String
            Get
                Return CType(Me("Save_RackNoBoard"),String)
            End Get
            Set
                Me("Save_RackNoBoard") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoBoard() As String
            Get
                Return CType(Me("Save_BoxNoBoard"),String)
            End Get
            Set
                Me("Save_BoxNoBoard") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoCopy() As String
            Get
                Return CType(Me("Save_RackNoCopy"),String)
            End Get
            Set
                Me("Save_RackNoCopy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoCopy() As String
            Get
                Return CType(Me("Save_BoxNoCopy"),String)
            End Get
            Set
                Me("Save_BoxNoCopy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoTrade() As String
            Get
                Return CType(Me("Save_RackNoTrade"),String)
            End Get
            Set
                Me("Save_RackNoTrade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoPatent() As String
            Get
                Return CType(Me("Save_RackNoPatent"),String)
            End Get
            Set
                Me("Save_RackNoPatent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoClear() As String
            Get
                Return CType(Me("Save_RackNoClear"),String)
            End Get
            Set
                Me("Save_RackNoClear") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoAccre() As String
            Get
                Return CType(Me("Save_RackNoAccre"),String)
            End Get
            Set
                Me("Save_RackNoAccre") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoSubs() As String
            Get
                Return CType(Me("Save_RackNoSubs"),String)
            End Get
            Set
                Me("Save_RackNoSubs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoContract() As String
            Get
                Return CType(Me("Save_RackNoContract"),String)
            End Get
            Set
                Me("Save_RackNoContract") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoAttorney() As String
            Get
                Return CType(Me("Save_RackNoAttorney"),String)
            End Get
            Set
                Me("Save_RackNoAttorney") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoOther() As String
            Get
                Return CType(Me("Save_RackNoOther"),String)
            End Get
            Set
                Me("Save_RackNoOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_RackNoMemo() As String
            Get
                Return CType(Me("Save_RackNoMemo"),String)
            End Get
            Set
                Me("Save_RackNoMemo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoTrade() As String
            Get
                Return CType(Me("Save_BoxNoTrade"),String)
            End Get
            Set
                Me("Save_BoxNoTrade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoPatent() As String
            Get
                Return CType(Me("Save_BoxNoPatent"),String)
            End Get
            Set
                Me("Save_BoxNoPatent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoClear() As String
            Get
                Return CType(Me("Save_BoxNoClear"),String)
            End Get
            Set
                Me("Save_BoxNoClear") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoAccre() As String
            Get
                Return CType(Me("Save_BoxNoAccre"),String)
            End Get
            Set
                Me("Save_BoxNoAccre") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoSubs() As String
            Get
                Return CType(Me("Save_BoxNoSubs"),String)
            End Get
            Set
                Me("Save_BoxNoSubs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoContract() As String
            Get
                Return CType(Me("Save_BoxNoContract"),String)
            End Get
            Set
                Me("Save_BoxNoContract") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoAttorney() As String
            Get
                Return CType(Me("Save_BoxNoAttorney"),String)
            End Get
            Set
                Me("Save_BoxNoAttorney") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoOther() As String
            Get
                Return CType(Me("Save_BoxNoOther"),String)
            End Get
            Set
                Me("Save_BoxNoOther") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Save_BoxNoMemo() As String
            Get
                Return CType(Me("Save_BoxNoMemo"),String)
            End Get
            Set
                Me("Save_BoxNoMemo") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DMS.My.MySettings
            Get
                Return Global.DMS.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
